play=OYNA
about=Hakkında
authors=Yazarlar:
contributors=Katkıda bulunanlar:
close=Kapat
complete=TAMAMLANDI
congratulation=Tebrikler!
you-loose=KAYBETTİN
try-it-again=Tekrar dene!
Turtle-Easy=Kaplumbağa - KOLAY
Flower-Medium=Çiçek - ORTA
Spider-Hard=Örümcek - ZOR
Cloud-Inferno=Bulut - CEHENNEM
Bug-Easy=Böcek - KOLAY
FourHills-Tricky=Dört Tepe - KAPANLI
startNewGame=Yeni oyun başlat
changeTheme=Tema değiştir
gameStatistics=Oyun istatistikleri
resumeGame=Oyuna dön
statistics=İstatistikler
numberOfGamesWon=Kazanılan oyun sayısı:
from= /
numberOfGamesWonWithUndoOrHints=İpucu kullanmadan kazanılan oyun sayısı:
highScore=En yüksek puan
achievements=Başarılar
layoutTurtle=Kazanıldı: "kaplumbağa" düzeni
layoutFlower=Kazanıldı: "çiçek" düzeni
layoutSpider=Kazanıldı: "örümcek" düzeni
layoutCloud=Kazanıldı: "bulut" düzeni
layoutBug=Kazanıldı: "böcek" düzeni
layoutFourHills=Kazanıldı: "dört tepe" düzeni
gameWonUnder8Minutes=8 dakikanın altında kazanılan oyun
gameWonWithoutHints=İpucu kullanmadan kazanılan oyun
gameWonWithoutUndo=Geri alma kullanmadan kazanılan oyun
1gameWon=En az bir oyun kazanıldı
5gamesWon=En az 5 oyun kazanıldı
10gamesWon=En az 10 oyun kazanıldı
back-to-menu=Menüye dön
points=Puan:
chooseLayout=Bir düzen seçin
closeStatistics=istatistikleri kapat
